name: MinevolutionCore
version: '1.0'
main: org.evasive.me.minevolutionCore.MinevolutionCore
api-version: '1.21'
commands:
  mgive:
    description: admin give command
  mdata:
    description: admin data command
  mspawnnpc:
    description: used to spawn npcs
  mpickaxeadd:
    description: used to add components to pickaxes
  pickaxeanvil:
    description: opens the pickaxe anvil
  forge:
    description: opens the forge
  blocks:
    description: block list command
  milestone:
    description: block milestone command

depend: [WorldGuard, Essentials]
