name: Minefinity
version: '1.0'
main: org.evasive.me.minefinity.Minefinity
api-version: '1.21'
commands:
  minegive:
    aliases: [mgive]
    permission: minefinity.minegive
    description: used to give minefinity items
  minedata:
    aliases: [mdata]
    permission: minefinity.minedata
    description: used to change player data in game
  minespawn:
    aliases: [mspawn]
    permission: minefinity.minespawn
    description: used to spawn custom npcs
  minepickaxeadd:
    aliases: [mpickaxeadd]
    permission: minefinity.mineaddpickaxe
    description: used to add components to pickaxes
  pickaxeanvil:
    aliases: [panvil]
    permission: minefinity.pickaxeanvil
    description: opens the pickaxe anvil gui
  blocks:
    aliases: [blockmaster, bm]
    description: opens the blocks gui
    permission: minefinity.blocks
  milestone:
    description: block milestone command
    permission: minefinity.milestone
  pay:
    description: used to pay player to player
    permission: minefinity.pay
  gamemode:
    aliases: [ gm ]
    permission: minefinity.gamemode
    description: used to set gamemode
  vanish:
    aliases: [ v ]
    permission: minefinity.vanish
    description: toggles player to visible/invisible
  staffmode:
    aliases: [ sm ]
    permission: minefinity.staffmode
    description: sets player to staff mode
  balance:
    aliases: [ bal ]
    permission: minefinity.balance
    description: checks the balance of a player
  economy:
    aliases: [ eco ]
    permission: minefinity.economy
    description: set/change player balance
  rename:
    permission: minefinity.rename
    description: sets the name of the item in your hand
  packetrefresh:
    aliases: [pr]
    permission: minefinity.packetrefresh
    description: refreshes the packets for a player
  setspawn:
    permission: minefinity.setspawn
    description: sets the spawn of the world
  spawn:
    permission: minefinity.spawn
    description: Brings a player to spawn
  speed:
    permission: minefinity.speed
    description: sets the players movement speed
  invesee:
    permission: minefinity.invesee
    description: Allows player to see the inventory of another player and edit it
  gamemodecreative:
    aliases: [gmc]
    permission: minefinity.gamemode
    description: Alternate creative command
  gamemodesurvival:
    aliases: [gms]
    permission: minefinity.gamemode
    description: Alternate survival command
  gamemodespectator:
    aliases: [gmsp]
    permission: minefinity.gamemode
    description: Alternate spectator command
  warp:
    permission: minefinity.warp
    description: Shows list of warps
  setwarp:
    permission: minefinity.setwarp
    description: Creates a warp for players to use

permissions:
  minefinity.gamemode:
    description: Allows the use of /gamemode
    default: op
  minefinity.staffmode:
    description: Allows the use of /staffmode
    default: op
  minefinity.vanish:
    description: Allows the use of /vanish
    default: op
  minefinity.minedata:
    description: Allows the use of /minedata
    default: op
  minefinity.pay:
    description: Allows the use of /pay
    default: true
  minefinity.balance:
    description: Allows the use of /balance
    default: true
  minefinity.balancetop:
    description: Allows the use of /balancetop
    default: true
  minefinity.blocks:
    description: Allows the use of /blocks
    default: true
  minefinity.pickaxeanvil:
    description: Allows the use of /pickaxeanvil
    default: true
  minefinity.economy:
    description: Allows the use of /economy
    default: op
  minefinity.rename:
    description: Allows the use of /rename
    default: op
  minfinity.packetrefresh:
    description: Allows the use of /packetrefresh
    default: op
  minefinity.setspawn:
    description: Allows use of /setspawn
    default: op
  minefinity.spawn:
    description: Allows use of /spawn
    default: true
  minefinity.speed:
    description: Allows use of /speed
    default: op
  minefinity.invesee:
    description: Allows use of /invesee
    default: op
  minefinity.warp:
    description: Allows use of /warp
    default: true
  minefinity.setwarp:
    description: Allows use of /setwarp
    default: op

depend: [WorldGuard]
